name: workly
description: "문서 편집, 화이트보드 브레인스토밍, 태스크 관리 및 팀 커뮤니케이션을 위한 크로스플랫폼 실시간 협업 도구."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  supabase_flutter: ^2.8.4
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
